<?php
/** @var \MageSuite\GoogleOptimizeIntegration\ViewModel\Integration $viewModel */
$viewModel = $block->getViewModel();
$isIntegrationEnabled = $viewModel->isIntegrationEnabled();
$optimizeContainerId = $viewModel->getContainerId() ?: "";
$isAsyncScript = $viewModel->isAsyncScript();
?>

<?php if ($isIntegrationEnabled) : ?>
    <script
        <?= $isAsyncScript ? "async" : ""?>
        src="https://www.googleoptimize.com/optimize.js?id=<?= $block->escapeHtml($optimizeContainerId) ?>"
    >
    /* defer-ignore */</script>
<?php endif; ?>
