<?php
/** @var \MageSuite\GoogleOptimize\ViewModel\Integration $viewModel */
$viewModel = $block->getViewModel();
$isEnabled = $viewModel->isEnabled();

if ($isEnabled):
    $containerId = $viewModel->getContainerId() ?: "";
    $isAsync = $viewModel->isAsync();
    $isAntiFlickerEnabled = $viewModel->isAntiFlickerEnabled();
?>
    <?php if ($isAntiFlickerEnabled): ?>
        <style>.async-hide { opacity: 0 !important}</style><script>/* defer-ignore */</script>
        <script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;})(window,document.documentElement,'async-hide','dataLayer',4000,{'<?= $block->escapeHtml($containerId) ?>':true});/* defer-ignore */</script>
    <?php endif; ?>

    <script<?= $isAsync ? "async" : ""?> src="https://www.googleoptimize.com/optimize.js?id=<?= $block->escapeHtml($containerId) ?>">/* defer-ignore */</script>

<?php endif; ?>